project_name: git-branches
release:
  github:
    owner: kyoh86
    name: git-branches
brew:
  install: |
    bin.install "git-branches"
    man1.install "git-branches.1"
  github:
    owner: kyoh86
    name: homebrew-tap
  folder: Formula
  homepage: https://github.com/kyoh86/git-branches
  description: Show each branch, upstream, author in git repository.
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - "386"
  main: .
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: git-branches
  hooks:
    pre: make man
archive:
  format: tar.gz
  name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
  - git-branches.1
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
